{{- $chart := include "chart.name" $ -}}
{{- $release := include "release.name" $ -}}

{{- if .Values.cronJobs -}}
  {{- range .Values.cronJobs -}}
    {{- $spec := . -}}
    {{- $component := $spec.component -}}
    {{- $name := include "components.jobName" (tuple $chart $component) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $name $component) | nindent 4 }}
spec:
  {{ include "components.cronJobs.options" $spec | nindent 2 }}
  jobTemplate:
    metadata:
      labels: {{ include "labels.app" (tuple $chart $release $name $component) | nindent 8 }}
    spec:
      {{ include "components.jobs.options" $spec | nindent 6 }}
      template:
        metadata:
          labels: {{ include "labels.app" (tuple $chart $release $name $component) | nindent 12 }}
        spec:
          containers:
          - {{ include "components.app" (tuple $ $spec ) | nindent 12 }}
          {{ include "components.volumes" (tuple $ $spec) | nindent 10 }}
          {{ include "components.nodeSelector" $ | nindent 10 }}
          {{ include "components.imagePullSecrets" $ | nindent 10 }}
          {{ include "components.priorityClassName" $spec| nindent 10 }}
          {{ include "components.restartPolicy" $spec.restartPolicy | nindent 10 }}
          {{ include "components.serviceAccount" (tuple $name $spec) | nindent 10 }}
          {{ include "components.tolerations" $ | nindent 10 }}
---
{{- end -}}
{{- end -}}
