{{- $chart := include "chart.name" $ -}}
{{- $release := include "release.name" $ -}}

{{- if .Values.dnsEndpoints -}}
{{- with .Values.dnsEndpoints -}}
  {{- $name := $chart -}}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $name) | nindent 4 }}
spec:
  endpoints:
  {{- range .items }}
  - {{ . | toYaml | nindent 4 }}
  {{- end }}
---
{{- end -}}
{{- end -}}