{{- $chart := include "chart.name" $ -}}
{{- $release := include "release.name" $ -}}
{{- $ingress := kindIs "slice" .Values.ingress | ternary (.Values.ingress) (list .Values.ingress) -}}

{{- range $ingress -}}
  {{- $spec := . -}}
  {{- if $spec -}}
    {{- $component := $spec.component  -}}
    {{- $name := include "components.ingressName" (tuple $chart $component) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $chart $component) | nindent 4 }}
  annotations:
    {{- $annotations := (include "annotations.ingress.combine" $spec.annotations) | fromJsonArray -}}
    {{- $annotations := (include "annotations.ingress.mergeSnippets" $annotations) | fromJsonArray -}}
    {{- range $annotations }}
    {{ .name }}: {{ .value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ $spec.className }}
  tls:
    {{- $tlsSecrets := (include "components.ingress.groupTLSSecrets" $spec) | fromJson -}}
    {{- range $secretName, $secretHosts := $tlsSecrets }}
  - hosts: {{ $secretHosts | toJson }}
    secretName: {{ $secretName }}
    {{- end }}
  rules:
    {{- range $spec.hosts }}
      {{- $host := . }}
    {{ if eq $host.hostname "*" }}
  - http:
    {{- else }}
  - host: {{ $host.hostname | quote }}
    http:
    {{- end }}
      paths:
      {{- range $host.paths }}
        {{ $hostPath := . }}
      - path: {{ $hostPath.path }}
        pathType: ImplementationSpecific
        backend:
          service:
          {{ if $hostPath.component }}
            {{- $service := (include "components.ingress.findService" (tuple $ $hostPath.component)) | fromJson -}}
            {{- $serviceName := index $service "name" }}
            {{- $servicePort :=  index $service "port" }}
            name: {{ $serviceName | required "matching service for component not found" }}
            port:
              name: {{ $servicePort | required "matching service port for component not found" }}
          {{- else }}
            name: {{ $hostPath.service | required "service must be specified" }}
            port:
              name: {{ $hostPath.portName | required "service port name must be specified" }}
          {{- end }}
      {{- end }}
    {{- end }}
---
{{- end -}}
{{- end -}}
