{{- $chart := include "chart.name" $ -}}
{{- $release := include "release.name" $ -}}
{{- $releaseObject := .Release -}}

{{- range .Values.deployments -}}
  {{- $spec := . -}}
  {{- $component := $spec.component -}}
  {{- if $spec.rbac -}}
    {{- $rbac := $spec.rbac -}}
    {{- $name := include "components.deploymentName" (tuple $ $component) -}}
    {{- if ($rbac.serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $name $component) | nindent 4 }}
---
    {{- end -}}
    {{- if $rbac.role -}}
      {{- $roleType := $rbac.role.namespaced | ternary "Role" "ClusterRole" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleType }}
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $name $component) | nindent 4 }}
      {{- if not $rbac.role.namespaced }}
    rbac.authorization.k8s.io/aggregate-to-infra-replicator-aggregate: "true"
      {{- end }}
rules:
      {{- range $rbac.role.rules }}
- apiGroups: {{ .apis | toJson }}
  resources: {{ .resources | toJson }}
  verbs: {{ .verbs | toJson }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $name $component) | nindent 4 }}
      {{- if ($rbac.binding).annotations }}
  annotations: {{ ($rbac.binding).annotations | toYaml | nindent 4 }}
      {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $roleType }}
  name: {{ $name }}
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ $releaseObject.Namespace }}
    {{- end -}}
  {{- end -}}
{{- end -}}