{{- $chart := include "chart.name" $ -}}
{{- $release := include "release.name" $ -}}

{{- if .Values.global.features.akvs -}}
  {{- $keyvault := .Values.secrets.keyvault -}}
  {{- range .Values.secrets.items }}
    {{- $spec := . -}}
    {{- $name := printf "%s-%s" $chart $spec.k8s_secret -}}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $chart) | nindent 4 }}
  annotations: {{ include "annotations.before" (dict "weight" "-10") | nindent 4 }}
spec:
  vault:
    name: {{ $keyvault }}
    object:
      name: {{ $spec.kv_secret }}
      type: secret
  output:
    secret:
      name: {{ $name }}
      dataKey: {{ $spec.variable }}
---
  {{- end }}
{{- end -}}

{{- if .Values.global.features.externalSecrets -}}
  {{- range .Values.externalSecrets -}}
    {{- $spec := . -}}
    {{- $provider := $spec.provider -}}
    {{- if $provider | eq "lockbox" -}}
      {{- $secretId := $spec.secretId -}}
      {{- $name := printf "%s-%s" $chart $spec.component -}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  labels: {{ include "labels.app" (tuple $chart $release $chart) | nindent 4 }}
  annotations: {{ include "annotations.before" (dict "weight" "-10") | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ printf "cluster-shared-%s-secrets-store" $provider }}
    kind: ClusterSecretStore
  target:
    name: {{ $name }}
  data:
      {{- range $spec.items }}
  - secretKey: {{ .variable }}
    remoteRef:
      key: {{ $secretId }}
      property: {{ .property }}
      {{- end }}
---
    {{- end -}}
  {{- end -}}
{{- end -}}