{{- $chart := include "chart.name" $ -}}
{{- $release := include "release.name" $ -}}

{{- if .Values.services -}}
  {{- range .Values.services }}
    {{- $spec := . -}}
    {{- $component := $spec.component -}}
    {{- $serviceName := include "components.serviceName" (tuple $ $spec) -}}
    {{- $deploymentName := include "components.deploymentName" (tuple $ $component) -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $spec.annotations }}
    {{ .name }}: {{ .value | quote }}
  {{- end }}
  name: {{ $serviceName }}
  labels: {{ include "labels.app" (tuple $chart $release $deploymentName $component) | nindent 4 }}
spec:
  type: {{ $spec.type }}
{{ if not (empty $spec.clusterIP) }}
  clusterIP: {{ $spec.clusterIP }}
{{ end }}
  ports:
{{- with $spec.port }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
    name: {{ .name }}
{{- end }}
{{- range $spec.extraPorts }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
    name: {{ .name }}
{{- end }}
  selector:
  {{ include "labels.selector" (tuple $deploymentName $release) | nindent 4 }}
---
{{- end -}}
{{- end -}}
